"""Add Imoveis models

Revision ID: def0664d357e
Revises: 3a474861868f
Create Date: 2026-07-08 03:05:52.283125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'def0664d357e'
down_revision: Union[str, None] = '3a474861868f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=5), nullable=True),
    sa.Column('finalidade', sa.Enum('venda', 'aluguer', name='finalidadeimovelenum'), nullable=True),
    sa.Column('tipo_imovel', sa.Enum('apartamento', 'moradia', 'terreno', 'loja', 'escritorio', 'armazem', 'outro', name='tipoimovelenum'), nullable=False),
    sa.Column('tipologia', sa.String(length=50), nullable=True),
    sa.Column('quartos', sa.Integer(), nullable=True),
    sa.Column('casas_de_banho', sa.Integer(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('endereco_completo', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=True),
    sa.Column('avaliacao_media', sa.Float(), nullable=True),
    sa.Column('total_avaliacoes', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['perfis_vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imoveis_id'), 'imoveis', ['id'], unique=False)
    op.create_index(op.f('ix_imoveis_titulo'), 'imoveis', ['titulo'], unique=False)
    op.create_table('imagens_imovel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagens_imovel_id'), 'imagens_imovel', ['id'], unique=False)
    op.create_table('propostas_imovel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('valor_proposto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_negociacao', 'aceita', 'rejeitada', 'concluida', name='statuspropostaimovelenum'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propostas_imovel_id'), 'propostas_imovel', ['id'], unique=False)
    op.drop_index('ix_mensagens_chat_id', table_name='mensagens_chat')
    op.drop_table('mensagens_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_chat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('remetente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('destinatario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conteudo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lida', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['utilizadores.id'], name='mensagens_chat_destinatario_id_fkey'),
    sa.ForeignKeyConstraint(['remetente_id'], ['utilizadores.id'], name='mensagens_chat_remetente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mensagens_chat_pkey')
    )
    op.create_index('ix_mensagens_chat_id', 'mensagens_chat', ['id'], unique=False)
    op.drop_index(op.f('ix_propostas_imovel_id'), table_name='propostas_imovel')
    op.drop_table('propostas_imovel')
    op.drop_index(op.f('ix_imagens_imovel_id'), table_name='imagens_imovel')
    op.drop_table('imagens_imovel')
    op.drop_index(op.f('ix_imoveis_titulo'), table_name='imoveis')
    op.drop_index(op.f('ix_imoveis_id'), table_name='imoveis')
    op.drop_table('imoveis')
    # ### end Alembic commands ###